# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "application" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"path" VARCHAR NOT NULL,"create_project" BOOLEAN NOT NULL,"parent_id" BIGINT);
create table "field" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"model_id" BIGINT NOT NULL,"field_type" VARCHAR NOT NULL,"required" BOOLEAN NOT NULL,"related_model_id" BIGINT);
create table "model" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"application_id" BIGINT NOT NULL,"module_id" BIGINT);
alter table "application" add constraint "application_module_id" foreign key("parent_id") references "application"("id") on update NO ACTION on delete NO ACTION;
alter table "field" add constraint "field_related_model_id" foreign key("related_model_id") references "model"("id") on update NO ACTION on delete NO ACTION;
alter table "field" add constraint "field_model_id" foreign key("model_id") references "model"("id") on update NO ACTION on delete NO ACTION;
alter table "model" add constraint "model_application_id" foreign key("application_id") references "application"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "application" drop constraint "application_module_id";
alter table "field" drop constraint "field_related_model_id";
alter table "field" drop constraint "field_model_id";
alter table "model" drop constraint "model_application_id";
drop table "application";
drop table "field";
drop table "model";

